version: '3'

vars:
  WASM_PKG_DIR: packages/wasm-core/pkg
  COMMON_TYPES_DIR: packages/common-types
  CLIENT_DIR: packages/web-client
  SERVER_DIR: packages/server

tasks:
  # Development tasks
  dev:
    desc: Start development server with WASM auto-rebuild
    deps: [build:common-types, build:wasm]
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - npm run dev

  dev:client:
    desc: Start client development server only (without WASM rebuild)
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - npm run dev

  dev:wasm:
    desc: Build WASM in watch mode
    dir: packages/wasm-core
    cmds:
      - cargo watch -i pkg -s "wasm-pack build --target web --out-dir pkg"

  dev:server:
    desc: Start server development mode with auto-reload
    dir: '{{.SERVER_DIR}}'
    cmds:
      - npm run dev

  # Build tasks
  build:
    desc: Build everything (common-types + WASM + client + server)
    cmds:
      - task: build:common-types
      - task: build:wasm
      - task: build:client
      - task: build:server

  build:common-types:
    desc: Build common TypeScript type definitions
    dir: '{{.COMMON_TYPES_DIR}}'
    cmds:
      - npm run build
    sources:
      - src/**/*.ts
      - tsconfig.json
    generates:
      - dist/**/*.d.ts
      - dist/**/*.js

  build:wasm:
    desc: Build WASM module using wasm-pack
    dir: packages/wasm-core
    cmds:
      - wasm-pack build --target web --out-dir pkg
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - pkg/*.wasm
      - pkg/*.js
      - pkg/*.ts

  build:client:
    desc: Build client for production
    dir: '{{.CLIENT_DIR}}'
    deps: [build:common-types, build:wasm]
    cmds:
      - npm run build

  build:server:
    desc: Build server for production
    dir: '{{.SERVER_DIR}}'
    cmds:
      - npm run build
    sources:
      - src/**/*.ts
      - tsconfig.json
    generates:
      - dist/**/*.js
      - dist/**/*.d.ts

  # Test tasks
  test:
    desc: Run all tests
    cmds:
      - task: test:rust
      - task: test:wasm
      - task: test:server

  test:rust:
    desc: Run Rust unit tests
    cmds:
      - cargo test --workspace

  test:wasm:
    desc: Run WASM tests in headless browser
    dir: packages/wasm-core
    cmds:
      - wasm-pack test --headless --chrome

  test:server:
    desc: Run server unit tests
    dir: '{{.SERVER_DIR}}'
    cmds:
      - npm run test

  test:e2e:
    desc: Run E2E tests (Phase 1A-6+)
    cmds:
      - echo "E2E tests not yet implemented (Phase 1A-6+)"

  # Linting and formatting
  lint:
    desc: Run all linters
    cmds:
      - task: lint:rust
      - task: lint:ts
      - task: lint:server

  lint:rust:
    desc: Run cargo clippy
    cmds:
      - cargo clippy --workspace --all-targets -- -D warnings

  lint:ts:
    desc: Run ESLint on TypeScript files
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - npm run lint

  lint:server:
    desc: Run ESLint on server TypeScript files
    dir: '{{.SERVER_DIR}}'
    cmds:
      - npm run lint

  fmt:
    desc: Format all code
    cmds:
      - task: fmt:rust
      - task: fmt:ts

  fmt:rust:
    desc: Format Rust code
    cmds:
      - cargo fmt --all

  fmt:ts:
    desc: Format TypeScript code
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - npm run format || echo "Add format script to package.json if needed"

  # Dependency management
  deps:install:
    desc: Install all dependencies
    cmds:
      - echo "Installing Rust dependencies..."
      - cargo fetch
      - echo "Installing Node dependencies (npm workspaces)..."
      - npm install

  deps:update:
    desc: Update all dependencies
    cmds:
      - cargo update
      - npm update

  # Clean tasks
  clean:
    desc: Clean all build artifacts
    cmds:
      - task: clean:common-types
      - task: clean:wasm
      - task: clean:client
      - task: clean:server
      - cargo clean

  clean:common-types:
    desc: Clean common-types build artifacts
    dir: '{{.COMMON_TYPES_DIR}}'
    cmds:
      - npm run clean || rm -rf dist

  clean:wasm:
    desc: Clean WASM build artifacts
    cmds:
      - rm -rf packages/wasm-core/pkg
      - rm -rf packages/wasm-core/target

  clean:client:
    desc: Clean client build artifacts
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - rm -rf dist
      - rm -rf node_modules

  clean:server:
    desc: Clean server build artifacts
    dir: '{{.SERVER_DIR}}'
    cmds:
      - npm run clean || rm -rf dist
      - rm -rf node_modules

  # Utility tasks
  check:
    desc: Check if everything compiles without building
    cmds:
      - cargo check --workspace

  doctor:
    desc: Check if all required tools are installed
    cmds:
      - echo "Checking required tools..."
      - command -v cargo || echo "❌ cargo not found"
      - command -v wasm-pack || echo "❌ wasm-pack not found (install with 'cargo install wasm-pack')"
      - command -v node || echo "❌ node not found"
      - command -v npm || echo "❌ npm not found"
      - echo "✅ All checks complete"
